services:
  homepod-sensors:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${PAIRING_FILE_HOST}:/app/pairing.json:ro
